//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersistenciaModelo.ModeloFactAdmin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using DominioEntidades.ModeloFactAdmin;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class db_fact_admin_entities : DbContext
    {
        public db_fact_admin_entities()
            : base("name=db_fact_admin_entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cliente> cliente { get; set; }
        public DbSet<empresa> empresa { get; set; }
        public DbSet<formularios> formularios { get; set; }
        public DbSet<lexico> lexico { get; set; }
        public DbSet<producto> producto { get; set; }
        public DbSet<rel_usuario_rol_empresa> rel_usuario_rol_empresa { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    
        public virtual ObjectResult<producto> SPWB_GetListProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<producto>("SPWB_GetListProductos");
        }
    
        public virtual ObjectResult<producto> SPWB_GetListProductos(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<producto>("SPWB_GetListProductos", mergeOption);
        }
    }
}
