//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioEntidades.ModeloFactAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public int clin_cliente_id { get; set; }
        public string clvc_nombre { get; set; }
        public string clvc_apellido { get; set; }
        public string clvc_nit { get; set; }
        public string clvc_direccion { get; set; }
        public string clvc_email { get; set; }
        public Nullable<System.DateTime> cldt_fecha_nac { get; set; }
        public Nullable<System.DateTime> cldt_fecha_registro { get; set; }
        public string clvc_user_registro { get; set; }
        public Nullable<System.DateTime> clvc_fecha_modif { get; set; }
        public string clvc_user_modif { get; set; }
        public Nullable<sbyte> clbt_is_hidden { get; set; }
    }
}
