//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioEntidades.ModeloFactAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class formularios
    {
        public int foin_formulario_id { get; set; }
        public Nullable<long> rubi_rel_us_rol_emp { get; set; }
        public string fovc_nombre_form { get; set; }
        public string fovc_url { get; set; }
        public Nullable<bool> fobt_edit { get; set; }
        public Nullable<bool> fobt_delete { get; set; }
        public Nullable<bool> fobt_view { get; set; }
        public Nullable<System.DateTime> fodt_fecha_insert { get; set; }
        public string fovc_user_insert { get; set; }
        public Nullable<System.DateTime> fodt_fecha_update { get; set; }
        public string fovc_user_update { get; set; }
        public bool fobt_is_hidden { get; set; }
    }
}
