//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioEntidades.ModeloFactAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int prin_producto_id { get; set; }
        public Nullable<int> cain_categoria_id { get; set; }
        public string prvc_nombre_producto { get; set; }
        public Nullable<decimal> prdc_precio_producto { get; set; }
    }
}
