//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioEntidades.ModeloFactAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class rel_usuario_rol_empresa
    {
        public long rubi_rel_us_rol_emp { get; set; }
        public Nullable<long> embi_empresa_id { get; set; }
        public Nullable<int> roin_rol_id { get; set; }
        public Nullable<long> usbi_usuario_id { get; set; }
        public Nullable<System.DateTime> rudt_fecha_insert { get; set; }
        public string ruvc_user_insert { get; set; }
        public Nullable<System.DateTime> rudt_fecha_modif { get; set; }
        public string ruvc_user_modif { get; set; }
        public bool embt_is_hidden { get; set; }
    }
}
