//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioEntidades.ModeloFactAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public int roin_rol_id { get; set; }
        public string rovc_nombre_rol { get; set; }
        public Nullable<System.DateTime> rodt_fecha_insert { get; set; }
        public string rovc_user_insert { get; set; }
        public Nullable<System.DateTime> rodt_fecha_modif { get; set; }
        public string rovc_user_modif { get; set; }
        public bool robt_is_hidden { get; set; }
    }
}
