//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioEntidades.ModeloFactAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public long usbi_usuario_id { get; set; }
        public string usvc_usuario_cod { get; set; }
        public string usvc_nombre_usuario { get; set; }
        public string usvc_contraseña_usuario { get; set; }
        public Nullable<System.DateTime> usdt_fecha_registro { get; set; }
        public string usvc_user_registro { get; set; }
        public Nullable<System.DateTime> usdt_fecha_modif { get; set; }
        public string usvc_user_modif { get; set; }
        public bool usbt_is_hidden { get; set; }
    }
}
